[filetree]
hidden = [
    "worktrees",
    ".DS_Store",
    ".git",
    ".azureal",
    ".claude",
]

[healthscope]
dirs = ["/Users/macbookpro/AZUREAL/src"]

[sessions]
54bda9dc-c4b5-4ce5-abb4-3f8cc0916099 = "[RCR] health"
b32d8463-7f9c-4bfc-81ee-ca4557847d28 = "[GodFileModularize] event_loop.rs"
be2bf6e7-e67e-4e50-af05-c4d4679a9b69 = "[RCR] health"
615e1145-3069-41c8-a4ac-abbf6d668fe3 = "[MCR] health"
975a150b-942e-490a-a180-4f4ad8b0ecdc = "tesst"
b11fb363-7d09-4233-823d-41e9560e81fb = "[GFM] draw_output.rs"

[runcmds]
"Cargo run (debug)" = "cargo r"
"Cargo run (release)" = "cargo r --release"

[presetprompts]

[git]
