[filetree]
hidden = [
    "worktrees",
    ".git",
    ".claude",
    ".DS_Store",
]

[healthscope]
dirs = []

[runcmds]

[presetprompts]

[git]
"auto-rebase/azureal/files" = "true"
"auto-rebase/azureal/sessionadd" = "true"
