//! Git background operation polling
//!
//! Polls mpsc receivers for: commit message generation, squash merge progress,
//! generic background ops (archive/unarchive/create/delete/push/pull/rename),
//! and rebase operations.

use crate::app::App;

/// Poll commit message generation receiver. Returns true if needs redraw.
pub fn poll_commit_generation(app: &mut App) -> bool {
    let mut redraw = false;
    if let Some(ref mut panel) = app.git_actions_panel {
        if let Some(ref mut overlay) = panel.commit_overlay {
            if overlay.generating {
                if let Some(ref rx) = overlay.receiver {
                    if let Ok(result) = rx.try_recv() {
                        match result {
                            Ok(generated) => {
                                overlay.message = generated.message;
                                overlay.cursor = overlay.message.chars().count();
                                overlay.generating = false;
                                overlay.receiver = None;
                                let mut status = format!(
                                    "Commit message generated by {}",
                                    generated.generator_label
                                );
                                if let Some(notice) = generated.fallback_notice {
                                    status.push_str(&format!(" ({})", notice));
                                }
                                panel.result_message = Some((status, false));
                                redraw = true;
                            }
                            Err(err) => {
                                // Both backends failed — close overlay and show error
                                panel.commit_overlay = None;
                                panel.result_message = Some((err, true));
                                redraw = true;
                            }
                        }
                    }
                }
            }
        }
    }
    redraw
}

/// Poll squash merge progress receiver. Returns true if needs redraw.
pub fn poll_squash_merge(app: &mut App) -> bool {
    use crate::app::types::SquashMergeOutcome;

    let mut redraw = false;
    let mut merge_outcome: Option<SquashMergeOutcome> = None;
    let mut new_phase: Option<String> = None;
    if let Some(ref mut panel) = app.git_actions_panel {
        if let Some(ref rx) = panel.squash_merge_receiver {
            while let Ok(progress) = rx.try_recv() {
                if let Some(outcome) = progress.outcome {
                    panel.squash_merge_receiver = None;
                    merge_outcome = Some(outcome);
                    redraw = true;
                    break;
                }
                new_phase = Some(progress.phase);
                redraw = true;
            }
        }
    }
    if let Some(phase) = new_phase {
        app.loading_indicator = Some(phase);
    }
    if let Some(outcome) = merge_outcome {
        app.loading_indicator = None;
        match outcome {
            SquashMergeOutcome::Success {
                status_msg,
                branch,
                display_name,
                worktree_path,
            } => {
                app.git_actions_panel = None;
                app.post_merge_dialog = Some(crate::app::types::PostMergeDialog {
                    branch,
                    display_name,
                    worktree_path,
                    selected: 0,
                });
                app.set_status(status_msg);
                // Trigger immediate auto-rebase — main just got new commits
                app.last_auto_rebase_check =
                    std::time::Instant::now() - std::time::Duration::from_secs(10);
            }
            SquashMergeOutcome::Conflict {
                conflicted,
                auto_merged,
            } => {
                if let Some(ref mut p) = app.git_actions_panel {
                    p.conflict_overlay = Some(crate::app::types::GitConflictOverlay {
                        conflicted_files: conflicted,
                        auto_merged_files: auto_merged,
                        scroll: 0,
                        selected: 0,
                        continue_with_merge: true,
                    });
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                }
            }
            SquashMergeOutcome::Failed(msg) => {
                if let Some(ref mut p) = app.git_actions_panel {
                    p.result_message = Some((msg, true));
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                }
            }
        }
    }
    redraw
}

/// Poll background worktree/git operations (archive, unarchive, create,
/// delete, pull, push, rename, RCR). Returns true if needs redraw.
pub fn poll_background_ops(app: &mut App) -> bool {
    use crate::app::types::BackgroundOpOutcome;

    let mut redraw = false;
    let mut op_outcome: Option<BackgroundOpOutcome> = None;
    let mut new_phase: Option<String> = None;
    if let Some(ref rx) = app.background_op_receiver {
        while let Ok(progress) = rx.try_recv() {
            if let Some(outcome) = progress.outcome {
                app.background_op_receiver = None;
                op_outcome = Some(outcome);
                redraw = true;
                break;
            }
            if !progress.phase.is_empty() {
                new_phase = Some(progress.phase);
                redraw = true;
            }
        }
    }
    if let Some(phase) = new_phase {
        app.loading_indicator = Some(phase);
    }
    if let Some(outcome) = op_outcome {
        app.loading_indicator = None;
        match outcome {
            BackgroundOpOutcome::Archived => {
                app.set_status("Session archived");
                app.save_live_display_events();
                let _ = app.refresh_worktrees();
                app.load_session_output();
            }
            BackgroundOpOutcome::Unarchived {
                branch,
                display_name,
            } => {
                app.set_status(format!("Unarchived: {}", display_name));
                app.save_live_display_events();
                app.save_current_terminal();
                let _ = app.refresh_worktrees();
                if let Some(idx) =
                    app.worktrees.iter().position(|s| s.branch_name == branch)
                {
                    app.selected_worktree = Some(idx);
                    app.load_session_output();
                }
            }
            BackgroundOpOutcome::Created { branch } => {
                app.save_live_display_events();
                app.save_current_terminal();
                let _ = app.refresh_worktrees();
                if let Some(idx) =
                    app.worktrees.iter().position(|s| s.branch_name == branch)
                {
                    app.selected_worktree = Some(idx);
                    app.load_session_output();
                }
                // Enable auto-rebase by default for new worktrees
                if let Some(wt_path) = app.worktrees.iter()
                    .find(|wt| wt.branch_name == branch)
                    .and_then(|wt| wt.worktree_path.as_ref())
                {
                    crate::azufig::set_auto_rebase(wt_path, true);
                    app.auto_rebase_enabled.insert(branch.clone());
                }
            }
            BackgroundOpOutcome::Deleted {
                display_name,
                prev_idx,
                ..
            } => {
                app.set_status(format!("Deleted: {}", display_name));
                app.save_live_display_events();
                app.save_current_terminal();
                let _ = app.refresh_worktrees();
                app.selected_worktree = if app.worktrees.is_empty() {
                    None
                } else {
                    Some(prev_idx.min(app.worktrees.len() - 1))
                };
                app.load_session_output();
            }
            BackgroundOpOutcome::GitResult { message, is_error } => {
                // After a successful pull, trigger immediate auto-rebase of
                // all enabled worktrees by resetting the throttle timer.
                let is_pull = !is_error && message.starts_with("Pulled:");
                if let Some(ref mut p) = app.git_actions_panel {
                    p.result_message = Some((message, is_error));
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                }
                if is_pull {
                    app.last_auto_rebase_check =
                        std::time::Instant::now() - std::time::Duration::from_secs(10);
                }
            }
            BackgroundOpOutcome::RcrFinished(completion) => {
                app.load_session_output();
                app.update_title_session_name();
                let had_merge = completion.post_merge_dialog.is_some();
                if let Some(dialog) = completion.post_merge_dialog {
                    app.post_merge_dialog = Some(dialog);
                }
                app.set_status(completion.status_msg);
                // After RCR merge, trigger immediate auto-rebase
                if had_merge {
                    app.last_auto_rebase_check =
                        std::time::Instant::now() - std::time::Duration::from_secs(10);
                }
            }
            BackgroundOpOutcome::Renamed { new_branch } => {
                let _ = app.refresh_worktrees();
                // Re-select the renamed branch
                if let Some(idx) = app
                    .worktrees
                    .iter()
                    .position(|w| w.branch_name == new_branch)
                {
                    app.selected_worktree = Some(idx);
                }
                app.load_session_output();
                let display = crate::models::strip_branch_prefix(&new_branch);
                app.set_status(format!("Renamed → {}", display));
            }
            BackgroundOpOutcome::Failed(msg) => {
                app.set_status(msg);
            }
        }
    }
    redraw
}

/// Poll background rebase operations (separate from generic ops because
/// rebase has conflict overlay handling). Returns true if needs redraw.
pub fn poll_rebase_ops(app: &mut App) -> bool {
    use crate::app::types::BackgroundRebaseOutcome;

    let mut redraw = false;
    let mut rebase_outcome: Option<BackgroundRebaseOutcome> = None;
    if let Some(ref rx) = app.rebase_op_receiver {
        if let Ok(outcome) = rx.try_recv() {
            app.rebase_op_receiver = None;
            rebase_outcome = Some(outcome);
            redraw = true;
        }
    }
    if let Some(outcome) = rebase_outcome {
        app.loading_indicator = None;
        match outcome {
            BackgroundRebaseOutcome::Rebased(msg) => {
                if let Some(ref mut p) = app.git_actions_panel {
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                    p.result_message = Some((msg, false));
                }
            }
            BackgroundRebaseOutcome::UpToDate => {
                if let Some(ref mut p) = app.git_actions_panel {
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                    p.result_message =
                        Some(("Already up to date with main".to_string(), false));
                }
            }
            BackgroundRebaseOutcome::Conflict {
                conflicted,
                auto_merged,
            } => {
                if let Some(ref mut p) = app.git_actions_panel {
                    p.conflict_overlay = Some(crate::app::types::GitConflictOverlay {
                        conflicted_files: conflicted,
                        auto_merged_files: auto_merged,
                        scroll: 0,
                        selected: 0,
                        continue_with_merge: false,
                    });
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                }
            }
            BackgroundRebaseOutcome::Failed(e) => {
                if let Some(ref mut p) = app.git_actions_panel {
                    crate::tui::input_git_actions::refresh_changed_files(p);
                    crate::tui::input_git_actions::refresh_commit_log(p);
                    p.result_message = Some((format!("Rebase failed: {}", e), true));
                }
            }
        }
    }
    redraw
}
